# Generated by Django 4.2 on 2024-04-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitNice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название для привычки')),
                ('action', models.TextField(verbose_name='действие')),
                ('need_time', models.TimeField(verbose_name='сколько времени займет')),
                ('public', models.BooleanField(default=False, verbose_name='видно ли всем')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
        ),
        migrations.CreateModel(
            name='HabitGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название для привычки')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='во сколько')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('period', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='1 раз, во сколько дней повторять')),
                ('need_time', models.TimeField(verbose_name='сколько времени займет')),
                ('public', models.BooleanField(default=False, verbose_name='видно ли всем')),
                ('connect_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habitnice', verbose_name='приятная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
            },
        ),
    ]
