# Generated by Django 4.2 on 2024-04-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitnice',
            name='need_time',
        ),
    ]
